### PR TITLE
Add support for namespaced Vuex actions

### PR DESCRIPTION
**Pull request by michgeek**
This PR is in reference to issue #34 

This is adding the support for namespaced Vuex actions. In order to differentiate `mutations` from `actions` and respect Vuex convention, actions will not be uppercased as stated in https://github.com/MetinSeylan/Vue-Socket.io/issues/34#issuecomment-287652651

Instead actions are prefixed with `socket_` followed by the `camelCased` event name.
Ex. Equivalent of `mutation SOCKET_USER_MESSAGE` will be `action socket_userMessage`

```js
{
  mutations: {
    MY_MUTATION: (state) => { /*...*/ },
    ANOTHER_MUTATION: (state) => { /*...*/ },
    SOCKET_USER_MESSAGE: (state) => { /*...*/ }
  },
  actions: {
    otherAction: (context) => { /* ... */ }
    socket_userMessage: (context, payload) => {
      // ... do things ...
      context.dispatch('otherAction', payload);
      context.dispatch('anotherActionSomewhereElse', payload, {root: true});
      context.commit('MY_MUTATION', payload);
      context.commit('ANOTHER_MUTATION', payload);
      // ... More things
    }
  }
}
```

### CODE REVIEW

**Comment by michgeek** [comment]
It will also be a good idea to tag this version as `2.2.0` since it's introducing a new feature

**Comment by MarlBurroW** [comment]
Great ! Nice job

**Comment by michgeek** [comment]
Don't merge it yet! I will add the improvement for the native events

**Comment by michgeek** [comment]
Please test it 👍

**Comment by MarlBurroW** [comment]
Works fine with native events now @michgeek, thanks for the PR !

**Comment by MetinSeylan** [comment]
Right now updated version in alpha, but i think major update for Vuex actions & mutations. thank you @michgeek

**Comment by BonLouis** [comment]
Are native events implemented ?

I'm using 
```
"vue": "^2.5.2",
"vue-socket.io": "^2.1.1-b",
"vuex": "^3.0.1"
```
, and with this piece of code: 
```
actions: { // = methods
		socket_testAction: (a) => {
			console.log('action', a);
		},
		socket_action: () => {
			console.log('action');
		}
	},
	mutations: { // = update state
		SOCKET_CONNECT: (state, status) => {
			console.log('mutation');
			state.user.isConnected = true;
		},
		SOCKET_DISCONNECT: (state) => {
			state.user.connected = false;
		}
	},
```
, mutations are triggered, but not actions, even upper cased.
I expect mutation and action named CONNECT/connect to be triggered on the same time.

Am i missing something ?

**Pull request merged**
