### PR TITLE
Adds basic Vue 3 compatibility

### LINKED ISSUE #284: Uncaught TypeError: Cannot set property '$socket' of undefined
`TypeError on Vue 3 with Typescript while installing the plugin with the new createApp.use() API.

main.ts
```javascript
const vSocket = new VueSocketIO({
    debug: true,
    connection: 'http://localhost:4000',
    /*  vuex: {
         store,
         actionPrefix: 'SOCKET_',
         mutationPrefix: 'SOCKET_'
     }, */
    /*  options: { path: "/my-app/" } //Optional options */
})
createApp(App).use(store).use(vSocket).mount('#app')
```
the error is 
```javascript
vue-socketio.js?5132:10 Uncaught TypeError: Cannot set property '$socket' of undefined
    at t.value (vue-socketio.js?5132:10)
    at Object.use (runtime-core.esm-bundler.js?5c40:3360)
    at eval (main.ts?bc82:19)
    at Module../src/main.ts (app.js:1115)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1140)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
```
I think the problem is with the plugin installation while using Vue 3 with Typescript.

### PR DESCRIPTION
**Pull request by veryeasily**
This pull request adds Vue 3 compatibility which should fix #284.

Previously this fix was open as #287 but seems like it was maybe prematurely closed. I tested my changes out and they appear to work on both Vue 3 and Vue 2.

As a warning though, my vue 3 tests have not been super thorough because my application is having vue 3 problems with unrelated dependencies. This PR gets past the initial issue, but there may still be deeper problems to debug.

### CODE REVIEW

**Comment by soulsam480** [comment]
> This pull request adds Vue 3 compatibility which should fix #284.
> 
> Previously this fix was open as #287 but seems like it was maybe prematurely closed. I tested my changes out and they appear to work on both Vue 3 and Vue 2.
> 
> As a warning though, my vue 3 tests have not been super thorough because my application is having vue 3 problems with unrelated dependencies. This PR gets past the initial issue, but there may still be deeper problems to debug.

Very good opening the pr with the solution.

**Comment by hajoch** [comment]
Any updates?

**Comment by chuckntaylor** [comment]
Is this fix confirmed to be working?

**Comment by stefa168** [comment]
> 
> 
> Is this fix confirmed to be working?

Yes, it does fix error #284. While waiting for the pull request to be accepted I forked the repo and pushed a custom build of the plugin, because I needed it asap.

**Comment by chuckntaylor** [comment]
Thanks! I think I find myself in the same boat.

**Comment by stefa168** [comment]
> 
> 
> Thanks! I think I find myself in the same boat.

Actually, I forgot to add that the typings are also broken, if you're using Typescript.

The absolute minimum required to get everything to work is a definition of the custom properties:
```lang=ts
declare module '@vue/runtime-core' {
    interface ComponentCustomProperties {
        $socket: SocketIO.Socket,
    }
}
```
I placed this declaration in my app entrypoint.

**Comment by bayernjava** [comment]
Any updates?

**Comment by Richard1984** [comment]
@MetinSeylan could you merge it please?

**Comment by wkuinkc** [comment]
Happy to see this merged too.

**Comment by wkuinkc** [comment]
thanks for merging! I tried running npm update vue-socket.io and it still doesn't seem to be working

**Comment by stefa168** [comment]
@wkuinkc try changing your dependency to point to this repo instead of the npm package

**Comment by thibqn** [comment]
@MetinSeylan, the NPM version doesn't seem up to date. Is there an upcoming update ? It would be greatly appreciated !

**Pull request merged**
