### PR TITLE
fix vue 3 plugin install

### PR DESCRIPTION
**Pull request by weishijun14**

### CODE REVIEW

**Comment by jmia** [comment]
Hey there. I noticed your PR changes the global variable name from `$socket` to `$http`. Because of that, you'll still get errors when you try to emit, regardless of whether you call `$socket.emit` or `$http.emit`. 

I opened a PR on it but you can toss that and make the change yourself if you want. I'm still new to GitHub etiquette.

**Comment by soulsam480** [comment]
@MetinSeylan Hey, When this pr is getting merged ?? I mean may we have some info. Thanks for this amazing library!!

**Comment by MetinSeylan** [comment]
hey thanks for pr 🤩 backward compatibility is important for now, did you test it on vue2, if we merge this maybe old projects will be crash?

**Comment by weishijun14** [comment]
emmm, I haven't test on vue2,, so I decide close this pr.. :sweat::sweat:

**Comment by soulsam480** [comment]
Hey I think this will work for the validation and will install according to the vue version

```javascript
var version = Number(Vue.version.split(".")[0]);
    //if vue 3
    if (version === 3) {
      Vue.config.globalProperties.$socket = this.io;
      Vue.config.globalProperties.$vueSocketIo = this;
      Vue.mixin(Mixin);
      Logger.info("Vue-Socket.io plugin enabled");
    } else {
      Vue.prototype.$socket = this.io;
      Vue.prototype.$vueSocketIo = this;
      Vue.mixin(Mixin);
      Logger.info("Vue-Socket.io plugin enabled");
    }
```

**Comment by soulsam480** [comment]
from Vue 2 API reference https://vuejs.org/v2/api/#Vue-version
In Vue 3 the same API is unchanged. So I think this will work 100% in Vue 2x.

**Review by soulsam480 — COMMENTED** [review]
We can do this for both Vue2x and Vue 3

```javascript
 /**
   * Vue.js entry point
   * @param Vue
   */

  install(Vue) {
    var version = Number(Vue.version.split(".")[0]);
    //if vue 3
    if (version === 3) {
      Vue.config.globalProperties.$socket = this.io;
      Vue.config.globalProperties.$vueSocketIo = this;
      Vue.mixin(Mixin);
      Logger.info("Vue-Socket.io plugin enabled");
    } else {
      Vue.prototype.$socket = this.io;
      Vue.prototype.$vueSocketIo = this;
      Vue.mixin(Mixin);
      Logger.info("Vue-Socket.io plugin enabled");
    }
  }
```

**Pull request closed without merging**
